"""Platform reference data: the specialty catalogue and accreditation standards.

These are *starting points*, not fixed lists. Every institution can add, rename or
deactivate anything here at runtime through the API — this module simply means a new
deployment is not staring at an empty database.
"""

from __future__ import annotations

# --------------------------------------------------------------------------
# Specialties: (code, name, faculty_group, discipline, parent_code | None)
# --------------------------------------------------------------------------
SPECIALTIES: list[tuple[str, str, str, str, str | None]] = [
    # ---- Surgery ---------------------------------------------------------
    ("SURG", "Surgery", "Surgery", "medical", None),
    ("SURG-GEN", "General Surgery", "Surgery", "medical", "SURG"),
    ("SURG-PLAS", "Plastic Surgery", "Surgery", "medical", "SURG"),
    ("SURG-NEURO", "Neurosurgery", "Surgery", "medical", "SURG"),
    ("SURG-CTS", "Cardiothoracic Surgery", "Surgery", "medical", "SURG"),
    ("SURG-ORTHO", "Orthopaedic Surgery", "Surgery", "medical", "SURG"),
    ("SURG-PAED", "Paediatric Surgery", "Surgery", "medical", "SURG"),
    ("SURG-URO", "Urology", "Surgery", "medical", "SURG"),
    ("SURG-TRAUMA", "Trauma Surgery", "Surgery", "medical", "SURG"),
    ("SURG-VASC", "Vascular Surgery", "Surgery", "medical", "SURG"),
    ("SURG-TRANS", "Transplant Surgery", "Surgery", "medical", "SURG"),
    ("SURG-ENDO", "Endocrine Surgery", "Surgery", "medical", "SURG"),
    ("SURG-HPB", "Hepatobiliary Surgery", "Surgery", "medical", "SURG"),
    ("SURG-COLO", "Colorectal Surgery", "Surgery", "medical", "SURG"),
    ("SURG-BREAST", "Breast Surgery", "Surgery", "medical", "SURG"),
    ("SURG-MAS", "Minimal Access Surgery", "Surgery", "medical", "SURG"),
    ("SURG-BURN", "Burn Surgery", "Surgery", "medical", "SURG-PLAS"),
    ("SURG-HAND", "Hand Surgery", "Surgery", "medical", "SURG-PLAS"),
    ("SURG-MICRO", "Microsurgery", "Surgery", "medical", "SURG-PLAS"),
    ("SURG-CRANIO", "Craniofacial Surgery", "Surgery", "medical", "SURG-PLAS"),
    ("SURG-ONCOPL", "Oncoplastic Surgery", "Surgery", "medical", "SURG-PLAS"),
    ("SURG-MAXFAC", "Maxillofacial Surgery", "Surgery", "medical", "SURG"),
    # ---- Medicine --------------------------------------------------------
    ("MED", "Internal Medicine", "Medicine", "medical", None),
    ("MED-CARD", "Cardiology", "Medicine", "medical", "MED"),
    ("MED-NEPH", "Nephrology", "Medicine", "medical", "MED"),
    ("MED-NEURO", "Neurology", "Medicine", "medical", "MED"),
    ("MED-GAST", "Gastroenterology", "Medicine", "medical", "MED"),
    ("MED-PULM", "Pulmonology", "Medicine", "medical", "MED"),
    ("MED-ENDO", "Endocrinology", "Medicine", "medical", "MED"),
    ("MED-RHEU", "Rheumatology", "Medicine", "medical", "MED"),
    ("MED-DERM", "Dermatology", "Medicine", "medical", "MED"),
    ("MED-HAEM", "Haematology", "Medicine", "medical", "MED"),
    ("MED-ONCO", "Medical Oncology", "Medicine", "medical", "MED"),
    ("MED-PHARM", "Clinical Pharmacology", "Medicine", "medical", "MED"),
    ("MED-ID", "Infectious Diseases", "Medicine", "medical", "MED"),
    ("MED-GERI", "Geriatrics", "Medicine", "medical", "MED"),
    ("MED-ICU", "Intensive Care Medicine", "Medicine", "medical", "MED"),
    ("MED-FAM", "Family Medicine", "Medicine", "medical", None),
    ("MED-EM", "Emergency Medicine", "Medicine", "medical", None),
    ("MED-SPORT", "Sports Medicine", "Medicine", "medical", "MED"),
    ("MED-PALL", "Palliative Medicine", "Medicine", "medical", "MED"),
    # ---- Dentistry -------------------------------------------------------
    ("DENT", "Dentistry", "Dentistry", "dental", None),
    ("DENT-REST", "Restorative Dentistry", "Dentistry", "dental", "DENT"),
    ("DENT-ORAL", "Oral Surgery", "Dentistry", "dental", "DENT"),
    ("DENT-ORTHO", "Orthodontics", "Dentistry", "dental", "DENT"),
    ("DENT-PERIO", "Periodontology", "Dentistry", "dental", "DENT"),
    ("DENT-PROSTH", "Prosthodontics", "Dentistry", "dental", "DENT"),
    ("DENT-PAED", "Paediatric Dentistry", "Dentistry", "dental", "DENT"),
    ("DENT-COMM", "Community Dentistry", "Dentistry", "dental", "DENT"),
    ("DENT-MED", "Oral Medicine", "Dentistry", "dental", "DENT"),
    ("DENT-PATH", "Oral Pathology", "Dentistry", "dental", "DENT"),
    ("DENT-PH", "Dental Public Health", "Dentistry", "dental", "DENT"),
    ("DENT-IMPL", "Implantology", "Dentistry", "dental", "DENT"),
    # ---- Anaesthesia -----------------------------------------------------
    ("ANAES", "Anaesthesia", "Anaesthesia", "medical", None),
    ("ANAES-GEN", "General Anaesthesia", "Anaesthesia", "medical", "ANAES"),
    ("ANAES-CARD", "Cardiac Anaesthesia", "Anaesthesia", "medical", "ANAES"),
    ("ANAES-OBS", "Obstetric Anaesthesia", "Anaesthesia", "medical", "ANAES"),
    ("ANAES-PAIN", "Pain Medicine", "Anaesthesia", "medical", "ANAES"),
    ("ANAES-CRIT", "Critical Care", "Anaesthesia", "medical", "ANAES"),
    ("ANAES-PAED", "Paediatric Anaesthesia", "Anaesthesia", "medical", "ANAES"),
    ("ANAES-NEURO", "Neuroanaesthesia", "Anaesthesia", "medical", "ANAES"),
    ("ANAES-REG", "Regional Anaesthesia", "Anaesthesia", "medical", "ANAES"),
    # ---- Obstetrics & Gynaecology ---------------------------------------
    ("OBGYN", "Obstetrics & Gynaecology", "Obstetrics & Gynaecology", "medical", None),
    ("OBGYN-MFM", "Maternal & Fetal Medicine", "Obstetrics & Gynaecology", "medical", "OBGYN"),
    ("OBGYN-REPRO", "Reproductive Endocrinology & Infertility", "Obstetrics & Gynaecology", "medical", "OBGYN"),
    ("OBGYN-ONCO", "Gynaecological Oncology", "Obstetrics & Gynaecology", "medical", "OBGYN"),
    ("OBGYN-URO", "Urogynaecology", "Obstetrics & Gynaecology", "medical", "OBGYN"),
    # ---- Paediatrics -----------------------------------------------------
    ("PAED", "Paediatrics", "Paediatrics", "medical", None),
    ("PAED-NEO", "Neonatology", "Paediatrics", "medical", "PAED"),
    ("PAED-CARD", "Paediatric Cardiology", "Paediatrics", "medical", "PAED"),
    ("PAED-NEURO", "Paediatric Neurology", "Paediatrics", "medical", "PAED"),
    ("PAED-ONCO", "Paediatric Oncology", "Paediatrics", "medical", "PAED"),
    ("PAED-NEPH", "Paediatric Nephrology", "Paediatrics", "medical", "PAED"),
    ("PAED-ID", "Paediatric Infectious Diseases", "Paediatrics", "medical", "PAED"),
    # ---- Radiology -------------------------------------------------------
    ("RAD", "Radiology", "Radiology", "medical", None),
    ("RAD-DIAG", "Diagnostic Radiology", "Radiology", "medical", "RAD"),
    ("RAD-INTV", "Interventional Radiology", "Radiology", "medical", "RAD"),
    ("RAD-NEURO", "Neuroradiology", "Radiology", "medical", "RAD"),
    ("RAD-PAED", "Paediatric Radiology", "Radiology", "medical", "RAD"),
    ("RAD-BREAST", "Breast Imaging", "Radiology", "medical", "RAD"),
    ("RAD-NUC", "Nuclear Medicine", "Radiology", "medical", "RAD"),
    # ---- Pathology -------------------------------------------------------
    ("PATH", "Pathology", "Pathology", "medical", None),
    ("PATH-ANAT", "Anatomical Pathology", "Pathology", "medical", "PATH"),
    ("PATH-CHEM", "Chemical Pathology", "Pathology", "medical", "PATH"),
    ("PATH-HAEM", "Haematology & Blood Transfusion", "Pathology", "medical", "PATH"),
    ("PATH-MICRO", "Medical Microbiology", "Pathology", "medical", "PATH"),
    ("PATH-FOREN", "Forensic Pathology", "Pathology", "medical", "PATH"),
    ("PATH-IMMUN", "Immunology", "Pathology", "medical", "PATH"),
    # ---- ENT -------------------------------------------------------------
    ("ENT", "Otorhinolaryngology (ENT)", "ENT", "medical", None),
    ("ENT-OTO", "Otology & Neurotology", "ENT", "medical", "ENT"),
    ("ENT-RHINO", "Rhinology", "ENT", "medical", "ENT"),
    ("ENT-LARYN", "Laryngology", "ENT", "medical", "ENT"),
    ("ENT-HNS", "Head & Neck Surgery", "ENT", "medical", "ENT"),
    ("ENT-PAED", "Paediatric ENT", "ENT", "medical", "ENT"),
    # ---- Ophthalmology ---------------------------------------------------
    ("OPHTH", "Ophthalmology", "Ophthalmology", "medical", None),
    ("OPHTH-RETINA", "Vitreoretinal Surgery", "Ophthalmology", "medical", "OPHTH"),
    ("OPHTH-GLAUC", "Glaucoma", "Ophthalmology", "medical", "OPHTH"),
    ("OPHTH-CORNEA", "Cornea & External Eye Disease", "Ophthalmology", "medical", "OPHTH"),
    ("OPHTH-PAED", "Paediatric Ophthalmology & Strabismus", "Ophthalmology", "medical", "OPHTH"),
    ("OPHTH-OCUL", "Oculoplastics", "Ophthalmology", "medical", "OPHTH"),
    # ---- Psychiatry ------------------------------------------------------
    ("PSYCH", "Psychiatry", "Psychiatry", "medical", None),
    ("PSYCH-CHILD", "Child & Adolescent Psychiatry", "Psychiatry", "medical", "PSYCH"),
    ("PSYCH-ADDICT", "Addiction Psychiatry", "Psychiatry", "medical", "PSYCH"),
    ("PSYCH-FOREN", "Forensic Psychiatry", "Psychiatry", "medical", "PSYCH"),
    ("PSYCH-GERI", "Old Age Psychiatry", "Psychiatry", "medical", "PSYCH"),
    ("PSYCH-LIAIS", "Liaison Psychiatry", "Psychiatry", "medical", "PSYCH"),
    # ---- Population health ----------------------------------------------
    ("COMM", "Community Medicine", "Community & Public Health", "medical", None),
    ("PH", "Public Health", "Community & Public Health", "medical", None),
    ("PH-EPI", "Epidemiology", "Community & Public Health", "medical", "PH"),
    ("PH-OCC", "Occupational Health", "Community & Public Health", "medical", "PH"),
    ("LAB", "Laboratory Medicine", "Laboratory Medicine", "medical", None),
]


# --------------------------------------------------------------------------
# Accreditation standards.
#
# These encode the *shape* of each body's requirements against the platform's metric
# vocabulary. Targets are illustrative defaults that each institution must reconcile
# with the current published standard for its programme — the values are editable in
# the accreditation profile builder precisely because colleges revise them.
# --------------------------------------------------------------------------
ACCREDITATION_PROFILES: list[dict] = [
    {
        "body": "npmcn",
        "body_name": "National Postgraduate Medical College of Nigeria",
        "code": "NPMCN-DEPT-ACC",
        "name": "Departmental Training Accreditation",
        "version": "2024.1",
        "applies_to_programme_types": ["residency_junior", "residency_senior", "fellowship"],
        "description": (
            "Departmental accreditation for residency training. Targets shipped here are "
            "defaults for a full-accreditation department and must be checked against the "
            "College's current published guidelines before submission."
        ),
        "criteria": [
            {"section": "Faculty", "code": "F1", "title": "Accredited trainers in post",
             "metric": "consultant_count", "operator": "gte", "target_value": 4,
             "unit": "consultants", "weighting": "essential",
             "evidence_guidance": "Attach appointment letters and College fellowship certificates."},
            {"section": "Faculty", "code": "F2", "title": "Trainer to trainee ratio",
             "metric": "trainer_trainee_ratio", "operator": "lte", "target_value": 4,
             "unit": "trainees per trainer", "weighting": "essential"},
            {"section": "Clinical volume", "code": "C1", "title": "Annual major operations",
             "metric": "annual_major_operations", "operator": "gte", "target_value": 400,
             "unit": "procedures/year", "weighting": "essential"},
            {"section": "Clinical volume", "code": "C2", "title": "Annual admissions",
             "metric": "annual_admissions", "operator": "gte", "target_value": 800,
             "unit": "admissions/year", "weighting": "essential"},
            {"section": "Clinical volume", "code": "C3", "title": "Annual clinic attendances",
             "metric": "annual_clinic_attendances", "operator": "gte", "target_value": 1500,
             "unit": "attendances/year", "weighting": "desirable"},
            {"section": "Academic", "code": "A1", "title": "Weekly departmental academic meeting",
             "metric": "academic_activity_frequency", "operator": "gte", "target_value": 4,
             "unit": "sessions/month", "weighting": "essential",
             "parameters": {"activity_kinds": ["grand_round", "seminar", "journal_club"]}},
            {"section": "Academic", "code": "A2", "title": "Monthly mortality & morbidity meeting",
             "metric": "academic_activity_frequency", "operator": "gte", "target_value": 1,
             "unit": "sessions/month", "weighting": "essential",
             "parameters": {"activity_kinds": ["mortality_meeting", "morbidity_meeting"]}},
            {"section": "Research", "code": "R1", "title": "Trainee research output",
             "metric": "trainee_publication_rate", "operator": "gte", "target_value": 0.5,
             "unit": "publications per trainee", "weighting": "desirable"},
            {"section": "Governance", "code": "G1", "title": "Logbook validation discipline",
             "metric": "logbook_validation_rate", "operator": "gte", "target_value": 85,
             "unit": "%", "weighting": "essential"},
            {"section": "Governance", "code": "G2", "title": "Assessment completion",
             "metric": "assessment_completion_rate", "operator": "gte", "target_value": 90,
             "unit": "%", "weighting": "desirable"},
            {"section": "Infrastructure", "code": "I1", "title": "Operating theatres",
             "metric": "infrastructure", "operator": "gte", "target_value": 2,
             "unit": "theatres", "weighting": "essential",
             "parameters": {"capacity_key": "operating_theatres"}},
            {"section": "Infrastructure", "code": "I2", "title": "Intensive care beds",
             "metric": "infrastructure", "operator": "gte", "target_value": 4,
             "unit": "beds", "weighting": "essential",
             "parameters": {"capacity_key": "icu_beds"}},
            {"section": "Infrastructure", "code": "I3", "title": "Departmental library seats",
             "metric": "infrastructure", "operator": "gte", "target_value": 10,
             "unit": "seats", "weighting": "desirable",
             "parameters": {"capacity_key": "library_seats"}},
            {"section": "Infrastructure", "code": "I4", "title": "Skills laboratory stations",
             "metric": "infrastructure", "operator": "gte", "target_value": 2,
             "unit": "stations", "weighting": "desirable",
             "parameters": {"capacity_key": "skills_lab_stations"}},
        ],
    },
    {
        "body": "wacs",
        "body_name": "West African College of Surgeons",
        "code": "WACS-DEPT-ACC",
        "name": "Surgical Training Centre Accreditation",
        "version": "2023.2",
        "applies_to_programme_types": ["residency_senior", "fellowship"],
        "criteria": [
            {"section": "Faculty", "code": "WF1", "title": "Fellows of the College in post",
             "metric": "consultant_count", "operator": "gte", "target_value": 3,
             "unit": "fellows", "weighting": "essential"},
            {"section": "Clinical volume", "code": "WC1", "title": "Major operative volume",
             "metric": "annual_major_operations", "operator": "gte", "target_value": 500,
             "unit": "procedures/year", "weighting": "essential"},
            {"section": "Clinical volume", "code": "WC2", "title": "Emergency surgical cover",
             "metric": "annual_admissions", "operator": "gte", "target_value": 600,
             "unit": "admissions/year", "weighting": "essential"},
            {"section": "Academic", "code": "WA1", "title": "Structured teaching programme",
             "metric": "academic_activity_frequency", "operator": "gte", "target_value": 4,
             "unit": "sessions/month", "weighting": "essential"},
            {"section": "Academic", "code": "WA2", "title": "Clinicopathological conferences",
             "metric": "academic_activity_frequency", "operator": "gte", "target_value": 0.5,
             "unit": "sessions/month", "weighting": "desirable",
             "parameters": {"activity_kinds": ["clinicopathological_conference"]}},
            {"section": "Outcomes", "code": "WO1", "title": "Fellowship examination pass rate",
             "metric": "exam_pass_rate", "operator": "gte", "target_value": 50,
             "unit": "%", "weighting": "desirable"},
            {"section": "Infrastructure", "code": "WI1", "title": "Dedicated theatre sessions",
             "metric": "infrastructure", "operator": "gte", "target_value": 2,
             "unit": "theatres", "weighting": "essential",
             "parameters": {"capacity_key": "operating_theatres"}},
        ],
    },
    {
        "body": "mdcn",
        "body_name": "Medical & Dental Council of Nigeria",
        "code": "MDCN-HOUSE-ACC",
        "name": "Housemanship Training Institution Accreditation",
        "version": "2024.1",
        "applies_to_programme_types": ["housemanship", "internship"],
        "criteria": [
            {"section": "Supervision", "code": "MS1", "title": "Supervising consultants",
             "metric": "consultant_count", "operator": "gte", "target_value": 2,
             "unit": "consultants", "weighting": "essential"},
            {"section": "Supervision", "code": "MS2", "title": "House officer to supervisor ratio",
             "metric": "trainer_trainee_ratio", "operator": "lte", "target_value": 6,
             "unit": "house officers per supervisor", "weighting": "essential"},
            {"section": "Clinical exposure", "code": "MC1", "title": "Annual admissions",
             "metric": "annual_admissions", "operator": "gte", "target_value": 500,
             "unit": "admissions/year", "weighting": "essential"},
            {"section": "Clinical exposure", "code": "MC2", "title": "Outpatient exposure",
             "metric": "annual_clinic_attendances", "operator": "gte", "target_value": 1000,
             "unit": "attendances/year", "weighting": "essential"},
            {"section": "Teaching", "code": "MT1", "title": "Weekly clinical teaching",
             "metric": "academic_activity_frequency", "operator": "gte", "target_value": 4,
             "unit": "sessions/month", "weighting": "essential"},
            {"section": "Records", "code": "MR1", "title": "Logbook completion and validation",
             "metric": "logbook_validation_rate", "operator": "gte", "target_value": 80,
             "unit": "%", "weighting": "essential"},
        ],
    },
    {
        "body": "wacp",
        "body_name": "West African College of Physicians",
        "code": "WACP-DEPT-ACC",
        "name": "Faculty of Internal Medicine Training Accreditation",
        "version": "2023.1",
        "applies_to_programme_types": ["residency_junior", "residency_senior", "fellowship"],
        "criteria": [
            {"section": "Faculty", "code": "PF1", "title": "Accredited physician trainers",
             "metric": "consultant_count", "operator": "gte", "target_value": 4,
             "unit": "consultants", "weighting": "essential"},
            {"section": "Clinical volume", "code": "PC1", "title": "Annual medical admissions",
             "metric": "annual_admissions", "operator": "gte", "target_value": 1000,
             "unit": "admissions/year", "weighting": "essential"},
            {"section": "Academic", "code": "PA1", "title": "Journal club frequency",
             "metric": "academic_activity_frequency", "operator": "gte", "target_value": 2,
             "unit": "sessions/month", "weighting": "essential",
             "parameters": {"activity_kinds": ["journal_club"]}},
            {"section": "Academic", "code": "PA2", "title": "Grand rounds",
             "metric": "academic_activity_frequency", "operator": "gte", "target_value": 2,
             "unit": "sessions/month", "weighting": "essential",
             "parameters": {"activity_kinds": ["grand_round"]}},
            {"section": "Research", "code": "PR1", "title": "Active trainee research projects",
             "metric": "research_output", "operator": "gte", "target_value": 3,
             "unit": "projects", "weighting": "desirable"},
        ],
    },
    {
        "body": "nuc",
        "body_name": "National Universities Commission",
        "code": "NUC-CLIN-DEPT",
        "name": "Clinical Department Academic Returns",
        "version": "2024.1",
        "applies_to_programme_types": ["residency_junior", "residency_senior", "fellowship"],
        "criteria": [
            {"section": "Staffing", "code": "NS1", "title": "Academic staff establishment",
             "metric": "consultant_count", "operator": "gte", "target_value": 5,
             "unit": "academic staff", "weighting": "essential"},
            {"section": "Programmes", "code": "NP1", "title": "Accredited programmes offered",
             "metric": "programme_count", "operator": "gte", "target_value": 1,
             "unit": "programmes", "weighting": "essential"},
            {"section": "Research", "code": "NR1", "title": "Departmental publication output",
             "metric": "publication_count", "operator": "gte", "target_value": 5,
             "unit": "publications/year", "weighting": "desirable"},
            {"section": "Facilities", "code": "NF1", "title": "Library provision",
             "metric": "infrastructure", "operator": "gte", "target_value": 20,
             "unit": "seats", "weighting": "desirable",
             "parameters": {"capacity_key": "library_seats"}},
        ],
    },
]


# --------------------------------------------------------------------------
# Procedure catalogue seeds by faculty group.
# (code, name, category, grade)
# --------------------------------------------------------------------------
PROCEDURES: dict[str, list[tuple[str, str, str, str]]] = {
    "Surgery": [
        ("APPEND", "Appendicectomy", "general", "major"),
        ("HERN-ING", "Inguinal hernia repair", "general", "major"),
        ("HERN-UMB", "Umbilical hernia repair", "general", "major"),
        ("CHOLE-OPEN", "Open cholecystectomy", "hepatobiliary", "major"),
        ("CHOLE-LAP", "Laparoscopic cholecystectomy", "minimal access", "major"),
        ("LAPAROT", "Exploratory laparotomy", "general", "major"),
        ("THYROID", "Thyroidectomy", "endocrine", "major"),
        ("MASTECT", "Mastectomy", "breast", "major"),
        ("HAEMORR", "Haemorrhoidectomy", "colorectal", "major"),
        ("COLOST", "Colostomy formation", "colorectal", "major"),
        ("SPLIT-SKIN", "Split-thickness skin graft", "plastic", "intermediate"),
        ("DEBRIDE", "Wound debridement", "general", "minor"),
        ("ID-ABSCESS", "Incision and drainage of abscess", "general", "minor"),
        ("EXC-BIOPSY", "Excision biopsy", "general", "minor"),
        ("CIRCUM", "Circumcision", "urology", "minor"),
        ("CHEST-DRAIN", "Chest tube insertion", "thoracic", "minor"),
        ("CENTRAL-LINE", "Central venous catheterisation", "general", "minor"),
        ("URETH-CATH", "Urethral catheterisation", "urology", "minor"),
        ("SUPRAPUB", "Suprapubic cystostomy", "urology", "intermediate"),
        ("HERNIOTOMY", "Herniotomy (paediatric)", "paediatric", "major"),
    ],
    "Medicine": [
        ("LUMBAR-P", "Lumbar puncture", "neurology", "minor"),
        ("PLEURAL-T", "Pleural aspiration", "pulmonology", "minor"),
        ("ASCITIC-T", "Ascitic tap", "gastroenterology", "minor"),
        ("BONE-MARROW", "Bone marrow aspiration", "haematology", "intermediate"),
        ("ENDOSCOPY", "Upper GI endoscopy", "gastroenterology", "intermediate"),
        ("COLONOSCOPY", "Colonoscopy", "gastroenterology", "intermediate"),
        ("ECHO", "Transthoracic echocardiography", "cardiology", "intermediate"),
        ("HAEMODIAL", "Haemodialysis session", "nephrology", "intermediate"),
        ("RENAL-BIOP", "Renal biopsy", "nephrology", "major"),
        ("CENTRAL-LINE-M", "Central venous access", "critical care", "minor"),
        ("INTUBATION", "Endotracheal intubation", "critical care", "intermediate"),
        ("CARDIOVERT", "DC cardioversion", "cardiology", "intermediate"),
    ],
    "Obstetrics & Gynaecology": [
        ("SVD", "Spontaneous vaginal delivery", "obstetrics", "intermediate"),
        ("CS", "Caesarean section", "obstetrics", "major"),
        ("ASSISTED-D", "Assisted vaginal delivery", "obstetrics", "intermediate"),
        ("MVA", "Manual vacuum aspiration", "gynaecology", "minor"),
        ("D-AND-C", "Dilatation and curettage", "gynaecology", "minor"),
        ("MYOMECT", "Myomectomy", "gynaecology", "major"),
        ("TAH", "Total abdominal hysterectomy", "gynaecology", "major"),
        ("ECTOPIC", "Surgery for ectopic pregnancy", "gynaecology", "major"),
        ("EPISIOT", "Episiotomy and repair", "obstetrics", "minor"),
        ("CERV-CERC", "Cervical cerclage", "obstetrics", "intermediate"),
    ],
    "Paediatrics": [
        ("NEO-RESUS", "Neonatal resuscitation", "neonatology", "intermediate"),
        ("UMB-CATH", "Umbilical catheterisation", "neonatology", "intermediate"),
        ("PAED-LP", "Paediatric lumbar puncture", "general", "minor"),
        ("EXCHANGE-T", "Exchange blood transfusion", "neonatology", "major"),
        ("IO-ACCESS", "Intraosseous access", "emergency", "minor"),
        ("NG-TUBE", "Nasogastric tube insertion", "general", "minor"),
    ],
    "Anaesthesia": [
        ("GA", "General anaesthesia", "general", "major"),
        ("SPINAL", "Spinal anaesthesia", "regional", "intermediate"),
        ("EPIDURAL", "Epidural anaesthesia", "regional", "intermediate"),
        ("NERVE-BLOCK", "Peripheral nerve block", "regional", "intermediate"),
        ("RSI", "Rapid sequence induction", "general", "intermediate"),
        ("ART-LINE", "Arterial line insertion", "critical care", "minor"),
    ],
    "Dentistry": [
        ("EXTRACT", "Simple dental extraction", "oral surgery", "minor"),
        ("SURG-EXTRACT", "Surgical extraction", "oral surgery", "intermediate"),
        ("RCT", "Root canal treatment", "restorative", "intermediate"),
        ("SCALING", "Scaling and polishing", "periodontology", "minor"),
        ("RESTORATION", "Dental restoration", "restorative", "minor"),
        ("DENTURE", "Complete denture construction", "prosthodontics", "intermediate"),
        ("ORTHO-APPL", "Orthodontic appliance fitting", "orthodontics", "intermediate"),
    ],
}
