"""adaptive learning: reading, readiness, integrity, generation, psychometrics

Revision ID: 7abae32f9b10
Revises: fd24179be941
Create Date: 2026-07-31

Adds seventeen tables covering reading engagement, examination readiness,
examination conduct, AI generation with its editorial gate, and psychometrics;
and extends ``questions``, ``exam_papers``, ``exam_attempts`` and
``cme_resources`` with provenance and conduct columns.

Three things in here were not produced by autogenerate and should not be
"tidied" back to its output:

1. **Every foreign key and dropped constraint is named.** SQLite cannot ALTER
   in place, so Alembic rebuilds the table in batch mode — and it cannot
   rebuild an anonymous constraint. Autogenerate emits ``None`` for both
   ``create_foreign_key`` and ``drop_constraint``, which fails at runtime on
   SQLite and makes the downgrade unrunnable.

2. **Every NOT NULL column is added with a ``server_default``, which is then
   dropped.** Adding a NOT NULL column to a table that already holds rows
   fails without one. This is the dangerous class of migration bug: it passes
   against an empty CI database and fails against a populated production one.
   The default is removed immediately afterwards so the schema still matches
   the models, which declare Python-side defaults — this project runs
   ``alembic check`` with ``compare_server_default=True`` and would otherwise
   report drift.

3. **``editorial_status`` backfills differently per table.** Existing CME
   resources were curated by hand and are already in use, so they backfill to
   ``published`` and stay visible. Existing questions have never passed
   through a review gate that did not exist, so they backfill to ``draft``.
   Publishing them wholesale would defeat the control this migration adds on
   its first day.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from app.db.base import UtcDateTime

revision: str = '7abae32f9b10'
down_revision: str | None = 'fd24179be941'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrity_policies',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('org_unit_id', sa.String(length=32), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('require_fullscreen', sa.Boolean(), nullable=False),
    sa.Column('log_focus_changes', sa.Boolean(), nullable=False),
    sa.Column('log_clipboard_attempts', sa.Boolean(), nullable=False),
    sa.Column('block_copy_paste', sa.Boolean(), nullable=False),
    sa.Column('block_printing', sa.Boolean(), nullable=False),
    sa.Column('block_context_menu', sa.Boolean(), nullable=False),
    sa.Column('single_session_only', sa.Boolean(), nullable=False),
    sa.Column('randomise_question_order', sa.Boolean(), nullable=False),
    sa.Column('randomise_option_order', sa.Boolean(), nullable=False),
    sa.Column('pool_multiplier', sa.Float(), nullable=False),
    sa.Column('idle_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('auto_submit_on_expiry', sa.Boolean(), nullable=False),
    sa.Column('device_fingerprinting', sa.Boolean(), nullable=False),
    sa.Column('ip_anomaly_detection', sa.Boolean(), nullable=False),
    sa.Column('proctoring_mode', sa.String(length=24), nullable=False),
    sa.Column('require_explicit_consent', sa.Boolean(), nullable=False),
    sa.Column('consent_statement', sa.Text(), nullable=True),
    sa.Column('retain_events_days', sa.Integer(), nullable=False),
    sa.Column('focus_loss_notice_threshold', sa.Integer(), nullable=False),
    sa.Column('focus_loss_concern_threshold', sa.Integer(), nullable=False),
    sa.Column('rapid_response_seconds', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.Column('deleted_at', UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_integrity_policy_code')
    )
    with op.batch_alter_table('integrity_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrity_policies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrity_policies_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrity_policies_org_unit_id'), ['org_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrity_policies_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('generation_jobs',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('org_unit_id', sa.String(length=32), nullable=True),
    sa.Column('bank_id', sa.String(length=32), nullable=True),
    sa.Column('specialty_id', sa.String(length=32), nullable=True),
    sa.Column('requested_by_id', sa.String(length=32), nullable=True),
    sa.Column('target_user_id', sa.String(length=32), nullable=True),
    sa.Column('trigger', sa.String(length=24), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('training_level', sa.String(length=32), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('blueprint', sa.JSON(), nullable=False),
    sa.Column('difficulty_mix', sa.JSON(), nullable=False),
    sa.Column('requested_at', UtcDateTime(), nullable=False),
    sa.Column('started_at', UtcDateTime(), nullable=True),
    sa.Column('finished_at', UtcDateTime(), nullable=True),
    sa.Column('deadline_minutes', sa.Integer(), nullable=False),
    sa.Column('stage_log', sa.JSON(), nullable=False),
    sa.Column('knowledge_sources', sa.JSON(), nullable=False),
    sa.Column('generated_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('regeneration_rounds', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('released_paper_id', sa.String(length=32), nullable=True),
    sa.Column('released_at', UtcDateTime(), nullable=True),
    sa.Column('released_by_id', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bank_id'], ['question_banks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['released_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['released_paper_id'], ['exam_papers.id'], name='fk_generation_jobs_released_paper_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialties.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generation_jobs_bank_id'), ['bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_org_unit_id'), ['org_unit_id'], unique=False)
        batch_op.create_index('ix_generation_jobs_requested', ['tenant_id', 'requested_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_target_user_id'), ['target_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generation_jobs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_generation_jobs_tenant_stage', ['tenant_id', 'stage'], unique=False)

    op.create_table('engagement_snapshots',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('enrolment_id', sa.String(length=32), nullable=True),
    sa.Column('window_start', sa.Date(), nullable=False),
    sa.Column('window_end', sa.Date(), nullable=False),
    sa.Column('reading_score', sa.Float(), nullable=False),
    sa.Column('consistency_score', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('retention_score', sa.Float(), nullable=True),
    sa.Column('articles_opened', sa.Integer(), nullable=False),
    sa.Column('articles_completed', sa.Integer(), nullable=False),
    sa.Column('active_minutes', sa.Integer(), nullable=False),
    sa.Column('distinct_active_days', sa.Integer(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enrolment_id'], ['enrolments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'window_start', 'window_end', name='uq_engagement_window')
    )
    with op.batch_alter_table('engagement_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagement_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_snapshots_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_engagement_snapshots_tenant_user', ['tenant_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_engagement_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('paper_analyses',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('paper_id', sa.String(length=32), nullable=False),
    sa.Column('computed_at', UtcDateTime(), nullable=False),
    sa.Column('candidates', sa.Integer(), nullable=False),
    sa.Column('items', sa.Integer(), nullable=False),
    sa.Column('mean_percent', sa.Float(), nullable=True),
    sa.Column('sd_percent', sa.Float(), nullable=True),
    sa.Column('median_percent', sa.Float(), nullable=True),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('kr20', sa.Float(), nullable=True),
    sa.Column('cronbach_alpha', sa.Float(), nullable=True),
    sa.Column('sem', sa.Float(), nullable=True),
    sa.Column('mean_facility', sa.Float(), nullable=True),
    sa.Column('mean_discrimination', sa.Float(), nullable=True),
    sa.Column('blueprint_coverage', sa.JSON(), nullable=False),
    sa.Column('flagged_items', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_paper_analyses_paper_at', ['paper_id', 'computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_analyses_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_analyses_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('readiness_snapshots',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('enrolment_id', sa.String(length=32), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('target_examination', sa.String(length=160), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('confidence_low', sa.Float(), nullable=False),
    sa.Column('confidence_high', sa.Float(), nullable=False),
    sa.Column('evidence_coverage', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('influential_factors', sa.JSON(), nullable=False),
    sa.Column('indices', sa.JSON(), nullable=False),
    sa.Column('weights_used', sa.JSON(), nullable=False),
    sa.Column('delta_from_previous', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enrolment_id'], ['enrolments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readiness_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readiness_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_readiness_snapshots_enrolment_id'), ['enrolment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_readiness_snapshots_score'), ['score'], unique=False)
        batch_op.create_index('ix_readiness_snapshots_tenant_cat', ['tenant_id', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_readiness_snapshots_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_readiness_snapshots_user_date', ['user_id', 'as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_readiness_snapshots_user_id'), ['user_id'], unique=False)

    op.create_table('exam_consents',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('attempt_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('policy_id', sa.String(length=32), nullable=True),
    sa.Column('statement_shown', sa.Text(), nullable=False),
    sa.Column('camera_granted', sa.Boolean(), nullable=False),
    sa.Column('microphone_granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', UtcDateTime(), nullable=False),
    sa.Column('withdrawn_at', UtcDateTime(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['integrity_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'user_id', name='uq_exam_consent_attempt')
    )
    with op.batch_alter_table('exam_consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_consents_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_consents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_consents_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_consents_user_id'), ['user_id'], unique=False)

    op.create_table('integrity_events',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('attempt_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', UtcDateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('question_sequence', sa.Integer(), nullable=True),
    sa.Column('device_hash', sa.String(length=64), nullable=True),
    sa.Column('network_hash', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrity_events', schema=None) as batch_op:
        batch_op.create_index('ix_integrity_events_attempt_at', ['attempt_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrity_events_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrity_events_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrity_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrity_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrity_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('integrity_reports',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('attempt_id', sa.String(length=32), nullable=False),
    sa.Column('policy_id', sa.String(length=32), nullable=True),
    sa.Column('generated_at', UtcDateTime(), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('event_counts', sa.JSON(), nullable=False),
    sa.Column('focus_loss_count', sa.Integer(), nullable=False),
    sa.Column('focus_loss_seconds', sa.Integer(), nullable=False),
    sa.Column('clipboard_attempts', sa.Integer(), nullable=False),
    sa.Column('distinct_devices', sa.Integer(), nullable=False),
    sa.Column('distinct_networks', sa.Integer(), nullable=False),
    sa.Column('rapid_responses', sa.Integer(), nullable=False),
    sa.Column('was_auto_submitted', sa.Boolean(), nullable=False),
    sa.Column('observations', sa.JSON(), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=32), nullable=True),
    sa.Column('reviewed_at', UtcDateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('candidate_statement', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['policy_id'], ['integrity_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', name='uq_integrity_report_attempt')
    )
    with op.batch_alter_table('integrity_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrity_reports_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrity_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrity_reports_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrity_reports_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('item_analyses',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('paper_id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('computed_at', UtcDateTime(), nullable=False),
    sa.Column('candidates', sa.Integer(), nullable=False),
    sa.Column('facility', sa.Float(), nullable=True),
    sa.Column('discrimination', sa.Float(), nullable=True),
    sa.Column('discrimination_index', sa.Float(), nullable=True),
    sa.Column('mean_seconds', sa.Float(), nullable=True),
    sa.Column('distractor_stats', sa.JSON(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paper_id', 'question_id', name='uq_item_analysis')
    )
    with op.batch_alter_table('item_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_analyses_paper_id'), ['paper_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_analyses_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_analyses_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_item_analyses_tenant_paper', ['tenant_id', 'paper_id'], unique=False)

    op.create_table('learning_plans',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('enrolment_id', sa.String(length=32), nullable=True),
    sa.Column('readiness_snapshot_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('authoring_source', sa.String(length=24), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('target_areas', sa.JSON(), nullable=False),
    sa.Column('approved_by_id', sa.String(length=32), nullable=True),
    sa.Column('approved_at', UtcDateTime(), nullable=True),
    sa.Column('completion_percent', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.Column('deleted_at', UtcDateTime(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enrolment_id'], ['enrolments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['readiness_snapshot_id'], ['readiness_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_plans_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_plans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_plans_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_plans_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_plans_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_learning_plans_user_status', ['user_id', 'status'], unique=False)

    op.create_table('question_drafts',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('lead_in', sa.Text(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_keys', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=False),
    sa.Column('topic', sa.String(length=160), nullable=True),
    sa.Column('subtopic', sa.String(length=160), nullable=True),
    sa.Column('blueprint_category', sa.String(length=64), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('difficulty_band', sa.String(length=24), nullable=True),
    sa.Column('bloom_level', sa.String(length=24), nullable=True),
    sa.Column('competency_domain', sa.String(length=40), nullable=True),
    sa.Column('competency_codes', sa.JSON(), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=False),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('shingles', sa.JSON(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=False),
    sa.Column('check_results', sa.JSON(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('duplicate_of_id', sa.String(length=32), nullable=True),
    sa.Column('promoted_question_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['generation_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promoted_question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_drafts_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_drafts_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_question_drafts_job_accepted', ['job_id', 'is_accepted'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_drafts_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_drafts_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('question_reviews',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('reviewer_id', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=False),
    sa.Column('to_status', sa.String(length=24), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('version_reviewed', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_reviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_question_reviews_question', ['question_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_reviews_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_reviews_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_reviews_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('question_versions',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('editorial_status', sa.String(length=24), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'version', name='uq_question_version')
    )
    with op.batch_alter_table('question_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_versions_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_versions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('reading_sessions',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=False),
    sa.Column('assignment_id', sa.String(length=32), nullable=True),
    sa.Column('opened_at', UtcDateTime(), nullable=False),
    sa.Column('closed_at', UtcDateTime(), nullable=True),
    sa.Column('active_seconds', sa.Integer(), nullable=False),
    sa.Column('max_scroll_percent', sa.Float(), nullable=False),
    sa.Column('section_completion_percent', sa.Float(), nullable=False),
    sa.Column('sections_completed', sa.JSON(), nullable=False),
    sa.Column('highlight_count', sa.Integer(), nullable=False),
    sa.Column('note_count', sa.Integer(), nullable=False),
    sa.Column('bookmark_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('reference_follow_count', sa.Integer(), nullable=False),
    sa.Column('videos_started', sa.Integer(), nullable=False),
    sa.Column('videos_completed', sa.Integer(), nullable=False),
    sa.Column('is_revisit', sa.Boolean(), nullable=False),
    sa.Column('captured_offline', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['cme_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['cme_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_sessions_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_sessions_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_sessions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_sessions_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_sessions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_reading_sessions_tenant_opened', ['tenant_id', 'opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reading_sessions_user_resource', ['user_id', 'resource_id'], unique=False)

    op.create_table('learning_plan_actions',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('plan_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('target_ref', sa.String(length=160), nullable=True),
    sa.Column('resource_id', sa.String(length=32), nullable=True),
    sa.Column('paper_id', sa.String(length=32), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completed_at', UtcDateTime(), nullable=True),
    sa.Column('evidence_ref', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['learning_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['cme_resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_plan_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_plan_actions_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_plan_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_plan_actions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_plan_actions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('reading_annotations',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('section_ref', sa.String(length=120), nullable=True),
    sa.Column('anchor', sa.JSON(), nullable=False),
    sa.Column('quoted_text', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('colour', sa.String(length=16), nullable=True),
    sa.Column('is_shared_with_supervisor', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.Column('deleted_at', UtcDateTime(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['cme_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['reading_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_annotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_annotations_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_annotations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_annotations_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_annotations_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_annotations_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_annotations_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reading_annotations_user_resource', ['user_id', 'resource_id'], unique=False)

    op.create_table('reading_events',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', UtcDateTime(), nullable=False),
    sa.Column('delta_seconds', sa.Integer(), nullable=False),
    sa.Column('scroll_percent', sa.Float(), nullable=True),
    sa.Column('section_ref', sa.String(length=120), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('synced_at', UtcDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['reading_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_events_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_reading_events_session_at', ['session_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reading_events_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('cme_resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authoring_source', sa.String(length=24), nullable=False, server_default=sa.text("'human'")))
        batch_op.add_column(sa.Column('editorial_status', sa.String(length=24), nullable=False, server_default=sa.text("'published'")))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('reviewed_by_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', UtcDateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('generation_job_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('ai_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sections', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('reference_entries', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('learning_objectives', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('clinical_pearls', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('frequently_tested_areas', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('landmark_trials', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('word_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
        batch_op.create_index(batch_op.f('ix_cme_resources_authoring_source'), ['authoring_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_cme_resources_editorial_status'), ['editorial_status'], unique=False)
        batch_op.create_foreign_key('fk_cme_resources_reviewed_by_id', 'users', ['reviewed_by_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_cme_resources_generation_job_id', 'generation_jobs', ['generation_job_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('device_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('network_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('integrity_outcome', sa.String(length=32), nullable=False, server_default=sa.text("'clean'")))
        batch_op.add_column(sa.Column('served_difficulties', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('was_auto_submitted', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.create_index(batch_op.f('ix_exam_attempts_session_token'), ['session_token'], unique=False)

    with op.batch_alter_table('exam_papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('integrity_policy_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('blueprint_profile', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
        batch_op.add_column(sa.Column('difficulty_mix', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
        batch_op.add_column(sa.Column('adaptive_difficulty', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('target_user_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('generated_by_job_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('cycle_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cycle_week', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_exam_papers_generated_by_job_id'), ['generated_by_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_papers_target_user_id'), ['target_user_id'], unique=False)
        batch_op.create_foreign_key('fk_exam_papers_integrity_policy_id', 'integrity_policies', ['integrity_policy_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_exam_papers_generated_by_job_id', 'generation_jobs', ['generated_by_job_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_exam_papers_target_user_id', 'users', ['target_user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authoring_source', sa.String(length=24), nullable=False, server_default=sa.text("'human'")))
        batch_op.add_column(sa.Column('editorial_status', sa.String(length=24), nullable=False, server_default=sa.text("'draft'")))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('generation_job_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('ai_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('published_at', UtcDateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_reviewed_at', UtcDateTime(), nullable=True))
        batch_op.add_column(sa.Column('retired_at', UtcDateTime(), nullable=True))
        batch_op.add_column(sa.Column('difficulty_band', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('bloom_level', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('competency_domain', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('blueprint_category', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('learning_objectives', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('evidence_level', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('publication_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cme_resource_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('shingles', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))
        batch_op.add_column(sa.Column('last_served_at', UtcDateTime(), nullable=True))
        batch_op.add_column(sa.Column('distractor_stats', sa.JSON(), nullable=False, server_default=sa.text("'{}'")))
        batch_op.create_index(batch_op.f('ix_questions_authoring_source'), ['authoring_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_blueprint_category'), ['blueprint_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_difficulty_band'), ['difficulty_band'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_editorial_status'), ['editorial_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_generation_job_id'), ['generation_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_last_reviewed_at'), ['last_reviewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_last_served_at'), ['last_served_at'], unique=False)
        batch_op.create_foreign_key('fk_questions_cme_resource_id', 'cme_resources', ['cme_resource_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_questions_generation_job_id', 'generation_jobs', ['generation_job_id'], ['id'], ondelete='SET NULL')


    # The server defaults above exist only so the NOT NULL columns could be
    # added to tables that already hold rows. Now that every existing row
    # has a value, drop them: the models declare Python-side defaults, and
    # leaving a database-level default would show up as schema drift under
    # `alembic check` (this project runs it with compare_server_default=True).
    with op.batch_alter_table('cme_resources', schema=None) as batch_op:
        batch_op.alter_column('authoring_source', existing_type=sa.String(length=24), server_default=None, existing_nullable=False)
        batch_op.alter_column('editorial_status', existing_type=sa.String(length=24), server_default=None, existing_nullable=False)
        batch_op.alter_column('version', existing_type=sa.Integer(), server_default=None, existing_nullable=False)
        batch_op.alter_column('sections', existing_type=sa.JSON(), server_default=None, existing_nullable=False)
        batch_op.alter_column('reference_entries', existing_type=sa.JSON(), server_default=None, existing_nullable=False)
        batch_op.alter_column('learning_objectives', existing_type=sa.JSON(), server_default=None, existing_nullable=False)
        batch_op.alter_column('clinical_pearls', existing_type=sa.JSON(), server_default=None, existing_nullable=False)
        batch_op.alter_column('frequently_tested_areas', existing_type=sa.JSON(), server_default=None, existing_nullable=False)
        batch_op.alter_column('landmark_trials', existing_type=sa.JSON(), server_default=None, existing_nullable=False)
        batch_op.alter_column('word_count', existing_type=sa.Integer(), server_default=None, existing_nullable=False)

    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.alter_column('integrity_outcome', existing_type=sa.String(length=32), server_default=None, existing_nullable=False)
        batch_op.alter_column('served_difficulties', existing_type=sa.JSON(), server_default=None, existing_nullable=False)
        batch_op.alter_column('was_auto_submitted', existing_type=sa.Boolean(), server_default=None, existing_nullable=False)

    with op.batch_alter_table('exam_papers', schema=None) as batch_op:
        batch_op.alter_column('blueprint_profile', existing_type=sa.JSON(), server_default=None, existing_nullable=False)
        batch_op.alter_column('difficulty_mix', existing_type=sa.JSON(), server_default=None, existing_nullable=False)
        batch_op.alter_column('adaptive_difficulty', existing_type=sa.Boolean(), server_default=None, existing_nullable=False)

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('authoring_source', existing_type=sa.String(length=24), server_default=None, existing_nullable=False)
        batch_op.alter_column('editorial_status', existing_type=sa.String(length=24), server_default=None, existing_nullable=False)
        batch_op.alter_column('version', existing_type=sa.Integer(), server_default=None, existing_nullable=False)
        batch_op.alter_column('learning_objectives', existing_type=sa.JSON(), server_default=None, existing_nullable=False)
        batch_op.alter_column('shingles', existing_type=sa.JSON(), server_default=None, existing_nullable=False)
        batch_op.alter_column('distractor_stats', existing_type=sa.JSON(), server_default=None, existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_questions_cme_resource_id', type_='foreignkey')
        batch_op.drop_constraint('fk_questions_generation_job_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_questions_last_served_at'))
        batch_op.drop_index(batch_op.f('ix_questions_last_reviewed_at'))
        batch_op.drop_index(batch_op.f('ix_questions_generation_job_id'))
        batch_op.drop_index(batch_op.f('ix_questions_editorial_status'))
        batch_op.drop_index(batch_op.f('ix_questions_difficulty_band'))
        batch_op.drop_index(batch_op.f('ix_questions_content_hash'))
        batch_op.drop_index(batch_op.f('ix_questions_blueprint_category'))
        batch_op.drop_index(batch_op.f('ix_questions_authoring_source'))
        batch_op.drop_column('distractor_stats')
        batch_op.drop_column('last_served_at')
        batch_op.drop_column('shingles')
        batch_op.drop_column('content_hash')
        batch_op.drop_column('cme_resource_id')
        batch_op.drop_column('publication_year')
        batch_op.drop_column('evidence_level')
        batch_op.drop_column('learning_objectives')
        batch_op.drop_column('blueprint_category')
        batch_op.drop_column('competency_domain')
        batch_op.drop_column('bloom_level')
        batch_op.drop_column('difficulty_band')
        batch_op.drop_column('retired_at')
        batch_op.drop_column('last_reviewed_at')
        batch_op.drop_column('published_at')
        batch_op.drop_column('ai_confidence')
        batch_op.drop_column('generation_job_id')
        batch_op.drop_column('version')
        batch_op.drop_column('editorial_status')
        batch_op.drop_column('authoring_source')

    with op.batch_alter_table('exam_papers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exam_papers_integrity_policy_id', type_='foreignkey')
        batch_op.drop_constraint('fk_exam_papers_generated_by_job_id', type_='foreignkey')
        batch_op.drop_constraint('fk_exam_papers_target_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_exam_papers_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_papers_generated_by_job_id'))
        batch_op.drop_column('cycle_week')
        batch_op.drop_column('cycle_year')
        batch_op.drop_column('generated_by_job_id')
        batch_op.drop_column('target_user_id')
        batch_op.drop_column('adaptive_difficulty')
        batch_op.drop_column('difficulty_mix')
        batch_op.drop_column('blueprint_profile')
        batch_op.drop_column('integrity_policy_id')

    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_attempts_session_token'))
        batch_op.drop_column('was_auto_submitted')
        batch_op.drop_column('served_difficulties')
        batch_op.drop_column('integrity_outcome')
        batch_op.drop_column('network_hash')
        batch_op.drop_column('device_hash')
        batch_op.drop_column('session_token')

    with op.batch_alter_table('cme_resources', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cme_resources_reviewed_by_id', type_='foreignkey')
        batch_op.drop_constraint('fk_cme_resources_generation_job_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cme_resources_editorial_status'))
        batch_op.drop_index(batch_op.f('ix_cme_resources_authoring_source'))
        batch_op.drop_column('word_count')
        batch_op.drop_column('landmark_trials')
        batch_op.drop_column('frequently_tested_areas')
        batch_op.drop_column('clinical_pearls')
        batch_op.drop_column('learning_objectives')
        batch_op.drop_column('reference_entries')
        batch_op.drop_column('sections')
        batch_op.drop_column('ai_confidence')
        batch_op.drop_column('generation_job_id')
        batch_op.drop_column('review_notes')
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by_id')
        batch_op.drop_column('version')
        batch_op.drop_column('editorial_status')
        batch_op.drop_column('authoring_source')

    with op.batch_alter_table('reading_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_reading_events_session_id'))
        batch_op.drop_index('ix_reading_events_session_at')
        batch_op.drop_index(batch_op.f('ix_reading_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_reading_events_client_uuid'))

    op.drop_table('reading_events')
    with op.batch_alter_table('reading_annotations', schema=None) as batch_op:
        batch_op.drop_index('ix_reading_annotations_user_resource')
        batch_op.drop_index(batch_op.f('ix_reading_annotations_user_id'))
        batch_op.drop_index(batch_op.f('ix_reading_annotations_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_reading_annotations_resource_id'))
        batch_op.drop_index(batch_op.f('ix_reading_annotations_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_reading_annotations_created_at'))
        batch_op.drop_index(batch_op.f('ix_reading_annotations_client_uuid'))

    op.drop_table('reading_annotations')
    with op.batch_alter_table('learning_plan_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_plan_actions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_learning_plan_actions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_learning_plan_actions_created_at'))
        batch_op.drop_index(batch_op.f('ix_learning_plan_actions_client_uuid'))

    op.drop_table('learning_plan_actions')
    with op.batch_alter_table('reading_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_reading_sessions_user_resource')
        batch_op.drop_index(batch_op.f('ix_reading_sessions_user_id'))
        batch_op.drop_index('ix_reading_sessions_tenant_opened')
        batch_op.drop_index(batch_op.f('ix_reading_sessions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_reading_sessions_resource_id'))
        batch_op.drop_index(batch_op.f('ix_reading_sessions_created_at'))
        batch_op.drop_index(batch_op.f('ix_reading_sessions_client_uuid'))
        batch_op.drop_index(batch_op.f('ix_reading_sessions_assignment_id'))

    op.drop_table('reading_sessions')
    with op.batch_alter_table('question_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_versions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_question_versions_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_versions_created_at'))

    op.drop_table('question_versions')
    with op.batch_alter_table('question_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_reviews_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_question_reviews_reviewer_id'))
        batch_op.drop_index(batch_op.f('ix_question_reviews_question_id'))
        batch_op.drop_index('ix_question_reviews_question')
        batch_op.drop_index(batch_op.f('ix_question_reviews_created_at'))

    op.drop_table('question_reviews')
    with op.batch_alter_table('question_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_drafts_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_question_drafts_job_id'))
        batch_op.drop_index('ix_question_drafts_job_accepted')
        batch_op.drop_index(batch_op.f('ix_question_drafts_created_at'))
        batch_op.drop_index(batch_op.f('ix_question_drafts_content_hash'))

    op.drop_table('question_drafts')
    with op.batch_alter_table('learning_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_learning_plans_user_status')
        batch_op.drop_index(batch_op.f('ix_learning_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_plans_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_learning_plans_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_learning_plans_created_at'))
        batch_op.drop_index(batch_op.f('ix_learning_plans_client_uuid'))

    op.drop_table('learning_plans')
    with op.batch_alter_table('item_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_item_analyses_tenant_paper')
        batch_op.drop_index(batch_op.f('ix_item_analyses_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_item_analyses_question_id'))
        batch_op.drop_index(batch_op.f('ix_item_analyses_paper_id'))
        batch_op.drop_index(batch_op.f('ix_item_analyses_created_at'))

    op.drop_table('item_analyses')
    with op.batch_alter_table('integrity_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrity_reports_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_integrity_reports_outcome'))
        batch_op.drop_index(batch_op.f('ix_integrity_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_integrity_reports_attempt_id'))

    op.drop_table('integrity_reports')
    with op.batch_alter_table('integrity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrity_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_integrity_events_kind'))
        batch_op.drop_index(batch_op.f('ix_integrity_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_integrity_events_client_uuid'))
        batch_op.drop_index(batch_op.f('ix_integrity_events_attempt_id'))
        batch_op.drop_index('ix_integrity_events_attempt_at')

    op.drop_table('integrity_events')
    with op.batch_alter_table('exam_consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_consents_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_consents_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_exam_consents_created_at'))
        batch_op.drop_index(batch_op.f('ix_exam_consents_attempt_id'))

    op.drop_table('exam_consents')
    with op.batch_alter_table('readiness_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readiness_snapshots_user_id'))
        batch_op.drop_index('ix_readiness_snapshots_user_date')
        batch_op.drop_index(batch_op.f('ix_readiness_snapshots_tenant_id'))
        batch_op.drop_index('ix_readiness_snapshots_tenant_cat')
        batch_op.drop_index(batch_op.f('ix_readiness_snapshots_score'))
        batch_op.drop_index(batch_op.f('ix_readiness_snapshots_enrolment_id'))
        batch_op.drop_index(batch_op.f('ix_readiness_snapshots_created_at'))

    op.drop_table('readiness_snapshots')
    with op.batch_alter_table('paper_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_analyses_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_paper_analyses_paper_id'))
        batch_op.drop_index('ix_paper_analyses_paper_at')
        batch_op.drop_index(batch_op.f('ix_paper_analyses_created_at'))

    op.drop_table('paper_analyses')
    with op.batch_alter_table('engagement_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagement_snapshots_user_id'))
        batch_op.drop_index('ix_engagement_snapshots_tenant_user')
        batch_op.drop_index(batch_op.f('ix_engagement_snapshots_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_engagement_snapshots_created_at'))

    op.drop_table('engagement_snapshots')
    with op.batch_alter_table('generation_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_generation_jobs_tenant_stage')
        batch_op.drop_index(batch_op.f('ix_generation_jobs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_stage'))
        batch_op.drop_index('ix_generation_jobs_requested')
        batch_op.drop_index(batch_op.f('ix_generation_jobs_org_unit_id'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_generation_jobs_bank_id'))

    op.drop_table('generation_jobs')
    with op.batch_alter_table('integrity_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrity_policies_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_integrity_policies_org_unit_id'))
        batch_op.drop_index(batch_op.f('ix_integrity_policies_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_integrity_policies_created_at'))

    op.drop_table('integrity_policies')
    # ### end Alembic commands ###
