"""add tenant branding assets

Revision ID: fd24179be941
Revises: 92c551a347ca
Create Date: 2026-07-31 07:13:01.355361
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from app.db.base import UtcDateTime

revision: str = 'fd24179be941'
down_revision: str | None = '92c551a347ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branding_assets',
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.String(length=32), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', UtcDateTime(), nullable=False),
    sa.Column('updated_at', UtcDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'kind', name='uq_branding_asset_tenant_kind')
    )
    with op.batch_alter_table('branding_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_branding_assets_checksum'), ['checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_branding_assets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_branding_assets_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branding_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branding_assets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_branding_assets_created_at'))
        batch_op.drop_index(batch_op.f('ix_branding_assets_checksum'))

    op.drop_table('branding_assets')
    # ### end Alembic commands ###
